version: "3.8"
services:
  bytecook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bytecook
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - OPENROUTER_API_KEY
